### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by frankzhangsyd** [frankzhangsyd/airflow-dag-action#1]
@Pf28
**Task:**
当前github actions支持的参数如下：
```
- name: 'Validate DAGs'
  uses: jayamanikharyono/airflow-dag-action@v2.3
  with:
    requirementsFile: tests/requirements.txt
    dagPaths: tests/dags
    varFile: tests/var.json
    connFile: tests/conns.json
    pluginPaths: tests/plugins
    loadExample: False
    accessToken: ${{ secrets.GITHUB_TOKEN }}
```
添加两个新的参数：`pythonVersion` 以及`airflowVersion`
目前code hardcode python 以及airflow 版本,需要加入版本号以支持不同的版本。
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/ca9f0793-ac33-49d7-93e5-5ea263d73f53">
**Steps:**
可能需要更新的地方：
1. https://github.com/frankzhangsyd/airflow-dag-action/blob/master/Dockerfile （版本号从外部variable)
2. https://github.com/frankzhangsyd/airflow-dag-action/blob/master/entrypoint.sh (加入新的参数）
3. https://github.com/frankzhangsyd/airflow-dag-action/blob/master/action.yml （加入新的参数，注意docker的创建）

开发的时候新建一个branch (based on main)

**Testing:**
This should work
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/d541ae88-c885-4b88-ab0a-3d850c3e33c6">

From this branch. https://github.com/frankzhangsyd/airflow-dag-action-test/pull/1
